server:
  port: 8080

spring:
  profiles:
    active: dev

  application:
    name: generator




#freemarker模版
  freemarker:
    #模板加载路径 按需配置 ,默认路径是 classpath:/templates/
    template-loader-path: classpath:/templates/
    # 编码格式
    charset: UTF-8
    # freemarker模板后缀 默认是 .ftl
    suffix: .html
    # 禁用模板缓存
    cache: false
    # 是否为此技术启用MVC视图分辨率。
    enabled: true
    # Content-Type值
    content-type: text/html
    settings:
      number_format: 0.## #freemarker默认数字每3位加逗号，这里重新格式化数字
